version: '3.1'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:11.1.1-rc
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    environment:
      - "MYSQL_ROOT_PASSWORD=soda0801!"
      - "TZ=Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

